import React, { useState, useEffect } from 'react';
import {
    FolderOpen,
    CheckCircle,
    Image as ImageIcon,
    Sparkles,
    Save,
    UploadCloud,
    Loader2,
    AlertCircle,
    FileText,
    Tags,
    ArrowRight,
    CheckSquare,
    Square,
    RefreshCw,
    Edit3,
    Settings,
    Key,
    Zap,
    User,
    Lock
} from 'lucide-react';

// --- CONFIGURATION ---
// Set to true to test the UI without the Python backend running
const USE_MOCK_API = false;
const API_BASE_URL = "/api";

// --- MOCK DATA GENERATORS ---
const mockImages = Array.from({ length: 12 }, (_, i) => `image_${i + 1}.jpg`);

const mockMetadata = (count) => Array.from({ length: count }, (_, i) => ({
    filename: `image_${i + 1}.jpg`,
    title: `Scenic View of Nature ${i + 1}`,
    description: `A beautiful high resolution shot of nature landscape number ${i + 1} with vibrant colors and natural lighting. Generated by Gemini 1.5 Flash.`,
    keywords: "nature, landscape, outdoors, sky, grass, summer, travel, scenic, environment, ai_generated",
    category: "Nature/Landscapes"
}));

// --- UTILITY COMPONENTS ---

const Card = ({ children, className = "" }) => (
    <div className={`bg-white rounded-xl shadow-sm border border-slate-200 overflow-hidden ${className}`}>
        {children}
    </div>
);

const Button = ({ onClick, disabled, variant = "primary", size = "md", icon: Icon, children, className = "" }) => {
    const baseStyles = "flex items-center justify-center font-medium transition-all focus:outline-none focus:ring-2 focus:ring-offset-2 disabled:opacity-50 disabled:cursor-not-allowed active:scale-95";

    const sizes = {
        sm: "px-3 py-1.5 text-sm",
        md: "px-4 py-2 text-sm",
        lg: "px-6 py-3 text-base"
    };

    const variants = {
        primary: "bg-blue-600 text-white hover:bg-blue-700 focus:ring-blue-500 shadow-blue-200 hover:shadow-md",
        secondary: "bg-white text-slate-700 border border-slate-300 hover:bg-slate-50 focus:ring-slate-200",
        success: "bg-emerald-600 text-white hover:bg-emerald-700 focus:ring-emerald-500 shadow-emerald-200 hover:shadow-md",
        danger: "bg-red-600 text-white hover:bg-red-700 focus:ring-red-500",
        ghost: "bg-transparent text-slate-600 hover:bg-slate-100 focus:ring-slate-200",
        gemini: "bg-gradient-to-r from-blue-500 via-purple-500 to-pink-500 text-white hover:opacity-90 border-0 shadow-purple-200 hover:shadow-md"
    };

    return (
        <button
            onClick={onClick}
            disabled={disabled}
            className={`${baseStyles} ${sizes[size]} ${variants[variant]} ${className}`}
        >
            {Icon && <Icon className={`mr-2 ${size === 'lg' ? 'w-5 h-5' : 'w-4 h-4'}`} />}
            {children}
        </button>
    );
};

const Badge = ({ children, color = "blue" }) => {
    const colors = {
        blue: "bg-blue-100 text-blue-800 border border-blue-200",
        green: "bg-green-100 text-green-800 border border-green-200",
        yellow: "bg-yellow-100 text-yellow-800 border border-yellow-200",
        purple: "bg-purple-100 text-purple-800 border border-purple-200",
        gray: "bg-slate-100 text-slate-800 border border-slate-200",
    };
    return (
        <span className={`px-2.5 py-0.5 rounded-full text-xs font-medium ${colors[color]}`}>
            {children}
        </span>
    );
};

const Modal = ({ isOpen, onClose, title, children }) => {
    if (!isOpen) return null;
    return (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 backdrop-blur-sm animate-in fade-in duration-200">
            <div className="bg-white rounded-xl shadow-2xl w-full max-w-md mx-4 overflow-hidden transform transition-all scale-100">
                <div className="px-6 py-4 border-b border-slate-100 flex justify-between items-center bg-slate-50/50">
                    <h3 className="font-bold text-lg text-slate-800">{title}</h3>
                    <button onClick={onClose} className="text-slate-400 hover:text-slate-600 transition-colors">
                        <span className="text-2xl leading-none">&times;</span>
                    </button>
                </div>
                <div className="p-6">
                    {children}
                </div>
            </div>
        </div>
    );
};

// --- MAIN APPLICATION ---

export default function App() {
    // --- STATE ---
    const [step, setStep] = useState(1);
    const [showSettings, setShowSettings] = useState(false);

    // Configuration State
    const [geminiKey, setGeminiKey] = useState('');
    const [ftpUser, setFtpUser] = useState('');
    const [ftpPass, setFtpPass] = useState('');

    // Step 1: Selection
    const [sourcePath, setSourcePath] = useState('/mnt/pictures');
    const [availableImages, setAvailableImages] = useState([]);
    const [selectedImages, setSelectedImages] = useState([]);
    const [loadingImages, setLoadingImages] = useState(false);
    const [projectName, setProjectName] = useState(`Stock_Batch_${new Date().toISOString().slice(0, 10)}`);

    // Step 2: Processing
    const [processingStatus, setProcessingStatus] = useState('idle');
    const [processResult, setProcessResult] = useState(null);
    const [errorMessage, setErrorMessage] = useState('');

    // Step 3: Editing
    const [metadataList, setMetadataList] = useState([]);
    const [savingStatus, setSavingStatus] = useState('idle');

    // Step 4: Upload
    const [uploadStatus, setUploadStatus] = useState('idle');
    const [uploadLogs, setUploadLogs] = useState([]);

    // --- INITIALIZATION ---
    useEffect(() => {
        const storedKey = localStorage.getItem('shutterstacker_gemini_key');
        const storedUser = localStorage.getItem('shutterstacker_ftp_user');
        const storedPass = localStorage.getItem('shutterstacker_ftp_pass');

        if (storedKey) setGeminiKey(storedKey);
        if (storedUser) setFtpUser(storedUser);
        if (storedPass) setFtpPass(storedPass);
    }, []);

    const saveSettings = () => {
        localStorage.setItem('shutterstacker_gemini_key', geminiKey);
        localStorage.setItem('shutterstacker_ftp_user', ftpUser);
        localStorage.setItem('shutterstacker_ftp_pass', ftpPass);
        setShowSettings(false);
    };

    // --- ACTIONS ---

    // Fetch Images
    const fetchImages = async () => {
        setLoadingImages(true);
        setErrorMessage('');
        setAvailableImages([]);
        setSelectedImages([]);

        try {
            if (USE_MOCK_API) {
                await new Promise(resolve => setTimeout(resolve, 800));
                setAvailableImages(mockImages);
                setSelectedImages(mockImages.slice(0, 8));
            } else {
                const response = await fetch(`${API_BASE_URL}/list-images?path=${encodeURIComponent(sourcePath)}`);
                if (!response.ok) throw new Error('Failed to load path');
                const data = await response.json();
                // Adapt backend response (list of objects) to frontend expectation (list of strings)
                const files = data
                    .filter(item => item.type === 'file')
                    .map(item => item.name);
                setAvailableImages(files);
                // Don't auto-select all, let user choose
                // setSelectedImages(files); 
            }
        } catch (err) {
            setErrorMessage(err.message);
        } finally {
            setLoadingImages(false);
        }
    };

    const toggleImageSelection = (img) => {
        if (selectedImages.includes(img)) {
            setSelectedImages(selectedImages.filter(i => i !== img));
        } else {
            setSelectedImages([...selectedImages, img]);
        }
    };

    const toggleSelectAll = () => {
        if (selectedImages.length === availableImages.length) {
            setSelectedImages([]);
        } else {
            setSelectedImages([...availableImages]);
        }
    };

    // Start AI Processing (Gemini V2 Logic)
    const startProcessing = async () => {
        if (!geminiKey && !USE_MOCK_API) {
            setErrorMessage("Google Gemini API Key is required for processing.");
            setShowSettings(true);
            return;
        }

        setProcessingStatus('processing');
        setErrorMessage('');

        try {
            if (USE_MOCK_API) {
                // Simulate Gemini API latency
                await new Promise(resolve => setTimeout(resolve, 2500));
                setProcessResult({
                    status: "success",
                    csv_path: "/app/processed/shutterstock.csv",
                    directory: "/app/processed/Stock_Batch_V2",
                    project_name: projectName
                });
            } else {
                const response = await fetch(`${API_BASE_URL}/process-with-gemini`, {
                    method: 'POST',
                    headers: { 'Content-Type': 'application/json' },
                    body: JSON.stringify({
                        source_folder: sourcePath,
                        selected_images: selectedImages,
                        project_name: projectName,
                        api_key: geminiKey
                    })
                });

                if (!response.ok) {
                    const errText = await response.text();
                    throw new Error(errText || 'Gemini Processing failed');
                }
                const data = await response.json();
                setProcessResult(data); // Expected: { status, csv_path, project_name }
            }
            setProcessingStatus('complete');
        } catch (err) {
            setErrorMessage(err.message);
            setProcessingStatus('error');
        }
    };

    // Load Metadata
    const loadMetadata = async () => {
        console.log("loadMetadata called", { processResult, USE_MOCK_API });
        if (!processResult?.project_name && !USE_MOCK_API) {
            console.error("Missing project_name in processResult");
            return;
        }

        try {
            let data;
            if (USE_MOCK_API) {
                await new Promise(resolve => setTimeout(resolve, 500));
                data = mockMetadata(selectedImages.length);
            } else {
                const url = `${API_BASE_URL}/get-metadata?project_name=${encodeURIComponent(processResult.project_name)}`;
                console.log("Fetching metadata from:", url);
                const response = await fetch(url);
                if (!response.ok) {
                    const txt = await response.text();
                    throw new Error(`Failed to fetch metadata: ${response.status} ${txt}`);
                }
                data = await response.json();
            }
            console.log("Metadata loaded:", data);
            setMetadataList(data);
            setStep(3);
        } catch (err) {
            console.error("loadMetadata error:", err);
            setErrorMessage("Failed to load CSV data: " + err.message);
        }
    };

    // Update metadata field
    const updateMetadataField = (index, field, value) => {
        const newList = [...metadataList];
        const key = Object.keys(newList[index]).find(k => k.toLowerCase() === field.toLowerCase()) || field.toLowerCase();
        newList[index] = { ...newList[index], [key]: value };
        setMetadataList(newList);
    };

    // Save Metadata
    const saveMetadata = async () => {
        setSavingStatus('saving');
        try {
            if (USE_MOCK_API) {
                await new Promise(resolve => setTimeout(resolve, 1500));
            } else {
                // Adapted to match backend EmbedRequest structure
                const response = await fetch(`${API_BASE_URL}/embed-metadata`, {
                    method: 'POST',
                    headers: { 'Content-Type': 'application/json' },
                    body: JSON.stringify({
                        project_name: processResult.project_name,
                        metadata: metadataList.map(item => ({
                            filename: item.Filename || item.filename,
                            title: item.Title || item.title || "",
                            description: item.Description || item.description || "",
                            keywords: item.Keywords || item.keywords || "",
                            category: item.Category || item.category || ""
                        }))
                    })
                });
                if (!response.ok) throw new Error('Failed to embed metadata');
                const resData = await response.json();
                if (resData.errors && resData.errors.length > 0) {
                    console.warn("Embed errors:", resData.errors);
                }
            }
            setSavingStatus('saved');
        } catch (err) {
            setErrorMessage(err.message);
            setSavingStatus('error');
        }
    };

    // Upload to Shutterstock
    const startUpload = async () => {
        if ((!ftpUser || !ftpPass) && !USE_MOCK_API) {
            setErrorMessage("Shutterstock FTP credentials required.");
            setShowSettings(true);
            return;
        }

        setUploadStatus('uploading');
        setUploadLogs(['Initializing FTP connection...', 'Authenticating...', 'Starting batch transfer...']);

        try {
            if (USE_MOCK_API) {
                const totalFiles = selectedImages.length;
                for (let i = 0; i < totalFiles; i++) {
                    await new Promise(r => setTimeout(r, 400));
                    setUploadLogs(prev => [...prev, `[SUCCESS] Uploaded: image_${i + 1}.jpg`]);
                }
                await new Promise(r => setTimeout(r, 300));
                setUploadLogs(prev => [...prev, 'Transfer Complete.']);
            } else {
                // Adapted to match backend UploadRequest structure
                const response = await fetch(`${API_BASE_URL}/upload`, {
                    method: 'POST',
                    headers: { 'Content-Type': 'application/json' },
                    body: JSON.stringify({
                        project_name: processResult.project_name,
                        ftp_user: ftpUser,
                        ftp_pass: ftpPass
                    })
                });

                if (!response.ok) throw new Error("Upload failed");
                const data = await response.json();
                setUploadLogs(prev => [...prev, ...data.uploaded.map(f => `Uploaded: ${f}`), 'All transfers complete.']);
                if (data.errors && data.errors.length > 0) {
                    setUploadLogs(prev => [...prev, ...data.errors.map(e => `[ERROR] ${e}`)]);
                }
            }
            setUploadStatus('complete');
        } catch (err) {
            setUploadLogs(prev => [...prev, `[ERROR] ${err.message}`]);
            setUploadStatus('error');
        }
    };

    // --- RENDER STEPS ---

    const renderStep1 = () => (
        <div className="space-y-6 animate-in fade-in duration-500">
            <div className="flex flex-col md:flex-row gap-4 items-end">
                <div className="flex-1 w-full">
                    <label className="block text-sm font-medium text-slate-700 mb-1">Project Name</label>
                    <input
                        type="text"
                        value={projectName}
                        onChange={(e) => setProjectName(e.target.value)}
                        className="w-full px-3 py-2 border border-slate-300 rounded-lg focus:ring-2 focus:ring-blue-500 outline-none shadow-sm"
                    />
                </div>
                <div className="flex-[2] w-full">
                    <label className="block text-sm font-medium text-slate-700 mb-1">Local Source Path (Docker Volume)</label>
                    <div className="flex gap-2">
                        <input
                            type="text"
                            value={sourcePath}
                            onChange={(e) => setSourcePath(e.target.value)}
                            className="flex-1 px-3 py-2 border border-slate-300 rounded-lg focus:ring-2 focus:ring-blue-500 outline-none shadow-sm font-mono text-sm"
                        />
                        <Button onClick={fetchImages} icon={FolderOpen} disabled={loadingImages}>
                            {loadingImages ? 'Scanning...' : 'Scan'}
                        </Button>
                    </div>
                </div>
            </div>

            {errorMessage && (
                <div className="p-4 bg-red-50 border border-red-100 text-red-700 rounded-lg flex items-center animate-in slide-in-from-top-2">
                    <AlertCircle className="w-5 h-5 mr-2" />
                    {errorMessage}
                </div>
            )}

            {availableImages.length > 0 && (
                <Card className="flex flex-col h-[60vh]">
                    <div className="p-4 border-b border-slate-100 flex justify-between items-center bg-slate-50">
                        <div className="flex items-center gap-2">
                            <Badge color="blue">{selectedImages.length} Selected</Badge>
                            <span className="text-slate-400 text-sm">of {availableImages.length} available</span>
                        </div>
                        <div className="flex gap-3">
                            <button
                                onClick={toggleSelectAll}
                                className="text-sm text-blue-600 hover:text-blue-800 font-medium transition-colors"
                            >
                                {selectedImages.length === availableImages.length ? 'Deselect All' : 'Select All'}
                            </button>
                        </div>
                    </div>
                    <div className="flex-1 overflow-y-auto p-4 custom-scrollbar bg-slate-50/50">
                        <div className="grid grid-cols-2 md:grid-cols-4 lg:grid-cols-5 gap-4">
                            {availableImages.map((img) => (
                                <div
                                    key={img}
                                    onClick={() => toggleImageSelection(img)}
                                    className={`
                    group relative aspect-square rounded-lg overflow-hidden cursor-pointer border-2 transition-all duration-200
                    ${selectedImages.includes(img)
                                            ? 'border-blue-500 ring-2 ring-blue-100 shadow-md scale-[0.98]'
                                            : 'border-transparent bg-white hover:border-slate-300 hover:shadow-sm'}
                  `}
                                >
                                    <div className="w-full h-full flex flex-col items-center justify-center text-slate-300 group-hover:text-slate-400 transition-colors">
                                        <ImageIcon className="w-10 h-10 mb-2 opacity-50" />
                                        <span className="text-[10px] font-mono opacity-60 uppercase tracking-widest">Raw/Jpg</span>
                                    </div>
                                    <div className="absolute top-2 right-2 transition-transform duration-200">
                                        {selectedImages.includes(img) ? (
                                            <CheckSquare className="w-5 h-5 text-blue-600 bg-white rounded-sm" />
                                        ) : (
                                            <Square className="w-5 h-5 text-slate-300 bg-white/80 rounded-sm opacity-0 group-hover:opacity-100" />
                                        )}
                                    </div>
                                    <div className="absolute bottom-0 left-0 right-0 bg-gradient-to-t from-slate-900/80 to-transparent pt-6 pb-2 px-2">
                                        <p className="text-white text-xs truncate font-medium">{img}</p>
                                    </div>
                                </div>
                            ))}
                        </div>
                    </div>
                </Card>
            )}

            {selectedImages.length > 0 && (
                <div className="flex justify-end animate-in fade-in slide-in-from-bottom-4">
                    <Button onClick={() => setStep(2)} size="lg" icon={ArrowRight}>
                        Next: AI Analysis
                    </Button>
                </div>
            )}
        </div>
    );

    const renderStep2 = () => (
        <div className="flex flex-col items-center justify-center py-12 space-y-8 animate-in fade-in duration-500">
            <div className="text-center space-y-3 max-w-lg">
                <div className="inline-flex items-center justify-center p-3 bg-gradient-to-br from-purple-100 to-blue-100 rounded-2xl mb-2">
                    <Sparkles className="w-8 h-8 text-purple-600" />
                </div>
                <h2 className="text-3xl font-bold text-slate-800 tracking-tight">Gemini Vision AI</h2>
                <p className="text-slate-500 text-lg">
                    Process {selectedImages.length} images using Google's Multimodal AI. <br />
                    <span className="text-sm text-slate-400">Generates commercial-ready titles, descriptions & keywords.</span>
                </p>
            </div>

            <div className="relative my-6 group cursor-pointer" onClick={() => (!geminiKey) && setShowSettings(true)}>
                {/* Status Visualizer */}
                {processingStatus === 'idle' && (
                    <div className={`p-1 rounded-full bg-gradient-to-r ${geminiKey ? 'from-blue-500 via-purple-500 to-pink-500' : 'from-slate-200 to-slate-300'}`}>
                        <div className="bg-white p-8 rounded-full relative">
                            {!geminiKey && <div className="absolute inset-0 flex items-center justify-center bg-white/80 rounded-full z-10 backdrop-blur-[1px]"><Key className="w-8 h-8 text-slate-400" /></div>}
                            <Sparkles className={`w-16 h-16 ${geminiKey ? 'text-purple-600' : 'text-slate-300'}`} />
                        </div>
                    </div>
                )}
                {processingStatus === 'processing' && (
                    <div className="relative p-1 rounded-full bg-gradient-to-r from-blue-500 via-purple-500 to-pink-500 animate-spin-slow">
                        <div className="bg-white p-8 rounded-full">
                            <Loader2 className="w-16 h-16 text-transparent bg-clip-text bg-gradient-to-r from-blue-600 to-purple-600 animate-spin" />
                        </div>
                    </div>
                )}
                {processingStatus === 'complete' && (
                    <div className="p-8 bg-emerald-50 border border-emerald-100 rounded-full shadow-emerald-100 shadow-lg animate-bounce-short">
                        <CheckCircle className="w-16 h-16 text-emerald-600" />
                    </div>
                )}
                {processingStatus === 'error' && (
                    <div className="p-8 bg-red-50 border border-red-100 rounded-full shadow-sm">
                        <AlertCircle className="w-16 h-16 text-red-600" />
                    </div>
                )}
            </div>

            <div className="w-full max-w-md space-y-4">
                {processingStatus === 'idle' && (
                    <>
                        {!geminiKey ? (
                            <Button onClick={() => setShowSettings(true)} variant="secondary" size="lg" className="w-full border-dashed border-2">
                                Configure API Key First
                            </Button>
                        ) : (
                            <Button onClick={startProcessing} variant="gemini" size="lg" className="w-full text-lg font-semibold tracking-wide">
                                <Sparkles className="w-5 h-5 mr-2 text-yellow-200" fill="currentColor" />
                                Generate Metadata
                            </Button>
                        )}
                    </>
                )}

                {processingStatus === 'processing' && (
                    <div className="space-y-2 text-center">
                        <p className="text-slate-800 font-medium animate-pulse bg-gradient-to-r from-blue-600 to-purple-600 bg-clip-text text-transparent">
                            Contacting Google Gemini Endpoint...
                        </p>
                        <p className="text-xs text-slate-400">Processing Batch: {projectName}</p>
                    </div>
                )}

                {processingStatus === 'complete' && (
                    <div className="space-y-4 animate-in fade-in slide-in-from-bottom-2">
                        <div className="bg-emerald-50 text-emerald-800 p-4 rounded-lg text-center border border-emerald-100 shadow-sm">
                            <p className="font-bold text-lg">Batch Complete!</p>
                            <p className="text-sm opacity-80 mt-1">Metadata generated & mapped.</p>
                        </div>

                        {errorMessage && (
                            <div className="p-3 bg-red-50 border border-red-100 text-red-700 rounded-lg text-sm flex items-center justify-center">
                                <AlertCircle className="w-4 h-4 mr-2" />
                                {errorMessage}
                            </div>
                        )}

                        <Button onClick={loadMetadata} variant="success" size="lg" className="w-full shadow-md">
                            Review & Edit Results
                        </Button>
                    </div>
                )}

                {processingStatus === 'error' && (
                    <div className="bg-red-50 text-red-800 p-4 rounded-lg text-center border border-red-100">
                        <p className="font-semibold">Analysis Failed</p>
                        <p className="text-sm mt-1 mb-3">{errorMessage}</p>
                        <Button onClick={() => setProcessingStatus('idle')} variant="secondary" size="sm">
                            Try Again
                        </Button>
                    </div>
                )}
            </div>
        </div>
    );

    const renderStep3 = () => (
        <div className="space-y-6 animate-in fade-in duration-500">
            <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-4 bg-white p-4 rounded-xl border border-slate-200 shadow-sm sticky top-20 z-40">
                <div>
                    <h2 className="text-xl font-bold text-slate-800 flex items-center gap-2">
                        <Edit3 className="w-5 h-5 text-blue-600" />
                        Review & Edit
                    </h2>
                    <p className="text-xs text-slate-400 mt-1">Verify AI suggestions before writing to files.</p>
                </div>

                <div className="flex gap-2 w-full md:w-auto">
                    <Button
                        onClick={saveMetadata}
                        icon={savingStatus === 'saving' ? Loader2 : Save}
                        disabled={savingStatus === 'saving' || savingStatus === 'saved'}
                        className="flex-1 md:flex-none"
                    >
                        {savingStatus === 'saving' ? 'Embedding...' : 'Embed Metadata'}
                    </Button>
                    {savingStatus === 'saved' && (
                        <Button onClick={() => setStep(4)} variant="success" icon={ArrowRight} className="flex-1 md:flex-none animate-in fade-in">
                            Next: FTP Upload
                        </Button>
                    )}
                </div>
            </div>

            {savingStatus === 'saved' && (
                <div className="bg-emerald-50 text-emerald-700 px-4 py-3 rounded-lg border border-emerald-100 flex items-center shadow-sm animate-in slide-in-from-top-2">
                    <CheckCircle className="w-5 h-5 mr-2 flex-shrink-0" />
                    <span>ExifTool: Metadata written to XMP/IPTC headers successfully.</span>
                </div>
            )}

            <div className="space-y-4">
                {metadataList.map((item, idx) => (
                    <Card key={idx} className="flex flex-col md:flex-row gap-0 md:gap-6 p-0 hover:shadow-md transition-shadow group">
                        {/* Image Thumbnail */}
                        <div className="w-full md:w-64 h-48 md:h-auto bg-slate-100 flex-shrink-0 flex items-center justify-center border-b md:border-b-0 md:border-r border-slate-100 relative">
                            <ImageIcon className="w-12 h-12 text-slate-300 group-hover:text-slate-400 transition-colors" />
                            <div className="absolute top-2 left-2">
                                <Badge color="purple">AI Generated</Badge>
                            </div>
                        </div>

                        {/* Form Fields */}
                        <div className="flex-1 p-6 space-y-5">
                            <div className="flex items-center justify-between border-b border-slate-100 pb-3">
                                <span className="font-mono text-xs text-slate-500 bg-slate-100 px-2 py-1 rounded">{item.filename || item.Filename}</span>
                                <div className="flex items-center gap-2">
                                    <label className="text-xs font-bold text-slate-400 uppercase">Category</label>
                                    <select
                                        className="text-xs bg-blue-50 text-blue-700 border-none rounded px-2 py-1 font-medium focus:ring-2 focus:ring-blue-200 cursor-pointer outline-none"
                                        value={item.Category || item.category}
                                        onChange={(e) => updateMetadataField(idx, 'Category', e.target.value)}
                                    >
                                        <option>Nature/Landscapes</option>
                                        <option>Business/Finance</option>
                                        <option>Technology</option>
                                        <option>People</option>
                                        <option>Abstract</option>
                                        <option>Food/Drink</option>
                                    </select>
                                </div>
                            </div>

                            <div className="grid gap-5">
                                <div>
                                    <label className="block text-xs font-bold text-slate-500 uppercase mb-1.5">Title</label>
                                    <input
                                        type="text"
                                        value={item.title || item.Title || ""}
                                        onChange={(e) => updateMetadataField(idx, 'Title', e.target.value)}
                                        className="w-full px-3 py-2 text-sm border border-slate-200 rounded-lg focus:ring-2 focus:ring-blue-500 outline-none transition-all"
                                    />
                                </div>

                                <div>
                                    <label className="block text-xs font-bold text-slate-500 uppercase mb-1.5">Description</label>
                                    <textarea
                                        rows={2}
                                        value={item.description || item.Description || ""}
                                        onChange={(e) => updateMetadataField(idx, 'Description', e.target.value)}
                                        className="w-full px-3 py-2 text-sm border border-slate-200 rounded-lg focus:ring-2 focus:ring-blue-500 outline-none transition-all resize-none"
                                    />
                                </div>

                                <div>
                                    <label className="block text-xs font-bold text-slate-500 uppercase mb-1.5 flex items-center justify-between">
                                        <span className="flex items-center gap-1"><Tags className="w-3 h-3" /> Keywords</span>
                                        <span className="text-[10px] font-normal text-slate-400">Comma separated for Stock sites</span>
                                    </label>
                                    <textarea
                                        rows={3}
                                        value={item.keywords || item.Keywords || ""}
                                        onChange={(e) => updateMetadataField(idx, 'Keywords', e.target.value)}
                                        className="w-full px-3 py-2 text-xs leading-relaxed bg-slate-50 border border-slate-200 rounded-lg focus:ring-2 focus:ring-blue-500 outline-none transition-all font-mono resize-none text-slate-600"
                                    />
                                </div>
                            </div>
                        </div>
                    </Card>
                ))}
            </div>
        </div>
    );

    const renderStep4 = () => (
        <div className="max-w-3xl mx-auto py-12 space-y-8 animate-in fade-in duration-500">
            <div className="text-center space-y-2">
                <h2 className="text-2xl font-bold text-slate-800">Upload to Shutterstock</h2>
                <p className="text-slate-500">
                    Secure FTP transfer of {metadataList.length} tagged assets.
                </p>
            </div>

            <Card className="bg-slate-900 text-slate-300 p-0 font-mono text-xs sm:text-sm border-slate-800 flex flex-col h-[400px]">
                <div className="flex items-center px-4 py-2 border-b border-slate-800 bg-slate-950/50">
                    <div className="flex gap-1.5 mr-4">
                        <div className="w-2.5 h-2.5 rounded-full bg-red-500/50"></div>
                        <div className="w-2.5 h-2.5 rounded-full bg-amber-500/50"></div>
                        <div className="w-2.5 h-2.5 rounded-full bg-emerald-500/50"></div>
                    </div>
                    <span className="opacity-50">ftp.shutterstock.com:21</span>
                </div>
                <div className="flex-1 p-6 overflow-y-auto custom-scrollbar space-y-1.5">
                    {uploadLogs.length === 0 ? (
                        <div className="text-slate-600 italic flex flex-col items-center justify-center h-full gap-2">
                            <UploadCloud className="w-8 h-8 opacity-20" />
                            <span>Ready to initialize connection...</span>
                        </div>
                    ) : (
                        uploadLogs.map((log, i) => (
                            <div key={i} className="flex gap-2 animate-in fade-in slide-in-from-left-2 duration-300">
                                <span className="text-blue-500 select-none">{'>'}</span>
                                <span className={`${log.includes('[ERROR]') ? 'text-red-400' : log.includes('[SUCCESS]') ? 'text-emerald-400' : 'text-slate-300'}`}>
                                    {log}
                                </span>
                            </div>
                        ))
                    )}
                </div>
            </Card>

            <div className="flex justify-center gap-4">
                {uploadStatus === 'idle' && (
                    <Button onClick={startUpload} size="lg" icon={UploadCloud} className="shadow-lg hover:shadow-xl transform hover:-translate-y-0.5">
                        Start FTP Upload
                    </Button>
                )}
                {uploadStatus === 'uploading' && (
                    <Button disabled className="opacity-80 bg-slate-800 text-white" icon={Loader2} size="lg">
                        Uploading...
                    </Button>
                )}
                {uploadStatus === 'complete' && (
                    <Button variant="success" onClick={() => { setStep(1); setUploadStatus('idle'); }} size="lg" icon={RefreshCw}>
                        Start New Batch
                    </Button>
                )}
            </div>
        </div>
    );

    return (
        <div className="min-h-screen bg-slate-50 text-slate-900 font-sans pb-20">
            {/* Settings Modal */}
            <Modal isOpen={showSettings} onClose={() => setShowSettings(false)} title="System Configuration">
                <div className="space-y-6">
                    {/* Gemini Config */}
                    <div className="space-y-2">
                        <h4 className="text-sm font-bold text-slate-800 uppercase tracking-wider border-b border-slate-100 pb-1 flex items-center gap-2">
                            <Sparkles className="w-4 h-4 text-purple-500" /> AI Configuration
                        </h4>
                        <div>
                            <label className="block text-sm font-medium text-slate-700 mb-1">Google Gemini API Key</label>
                            <div className="relative">
                                <Key className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-slate-400" />
                                <input
                                    type="password"
                                    value={geminiKey}
                                    onChange={(e) => setGeminiKey(e.target.value)}
                                    className="w-full pl-9 pr-3 py-2 border border-slate-300 rounded-lg focus:ring-2 focus:ring-purple-500 outline-none transition-shadow"
                                    placeholder="AIzaSy..."
                                />
                            </div>
                            <p className="text-xs text-slate-400 mt-1">Required for generating metadata.</p>
                        </div>
                    </div>

                    {/* FTP Config */}
                    <div className="space-y-2">
                        <h4 className="text-sm font-bold text-slate-800 uppercase tracking-wider border-b border-slate-100 pb-1 flex items-center gap-2">
                            <UploadCloud className="w-4 h-4 text-blue-500" /> Shutterstock FTP
                        </h4>
                        <div className="grid grid-cols-1 gap-3">
                            <div>
                                <label className="block text-sm font-medium text-slate-700 mb-1">FTP Username</label>
                                <div className="relative">
                                    <User className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-slate-400" />
                                    <input
                                        type="text"
                                        value={ftpUser}
                                        onChange={(e) => setFtpUser(e.target.value)}
                                        className="w-full pl-9 pr-3 py-2 border border-slate-300 rounded-lg focus:ring-2 focus:ring-blue-500 outline-none transition-shadow"
                                        placeholder="user@example.com"
                                    />
                                </div>
                            </div>
                            <div>
                                <label className="block text-sm font-medium text-slate-700 mb-1">FTP Password</label>
                                <div className="relative">
                                    <Lock className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-slate-400" />
                                    <input
                                        type="password"
                                        value={ftpPass}
                                        onChange={(e) => setFtpPass(e.target.value)}
                                        className="w-full pl-9 pr-3 py-2 border border-slate-300 rounded-lg focus:ring-2 focus:ring-blue-500 outline-none transition-shadow"
                                        placeholder="••••••••"
                                    />
                                </div>
                            </div>
                        </div>
                        <p className="text-xs text-slate-400 mt-1">Credentials are stored locally in your browser.</p>
                    </div>

                    <div className="flex justify-end gap-2 pt-4 border-t border-slate-100">
                        <Button variant="secondary" onClick={() => setShowSettings(false)}>Cancel</Button>
                        <Button onClick={saveSettings}>Save Configuration</Button>
                    </div>
                </div>
            </Modal>

            {/* Header */}
            <header className="bg-white border-b border-slate-200 sticky top-0 z-50 shadow-sm">
                <div className="max-w-7xl mx-auto px-4 h-16 flex items-center justify-between">
                    <div
                        className="flex items-center gap-2 cursor-pointer group"
                        onClick={() => setStep(1)}
                    >
                        <div className="bg-red-50 p-1.5 rounded-lg group-hover:bg-red-100 transition-colors">
                            <ImageIcon className="w-6 h-6 text-red-600" />
                        </div>
                        <div className="flex flex-col">
                            <span className="text-xl font-bold tracking-tight text-slate-900 leading-none">Shutter<span className="text-red-600">Stacker</span></span>
                            <span className="text-[10px] font-bold text-purple-600 uppercase tracking-wider">SaaS Edition</span>
                        </div>
                    </div>
                    <div className="flex items-center gap-3">
                        {USE_MOCK_API && <Badge color="yellow">Simulation</Badge>}
                        <button
                            onClick={() => setShowSettings(true)}
                            className="p-2 text-slate-500 hover:bg-slate-100 rounded-full transition-colors relative"
                            title="Settings"
                        >
                            <Settings className="w-5 h-5" />
                            {(!geminiKey || !ftpUser) && <span className="absolute top-1.5 right-1.5 w-2 h-2 bg-red-500 rounded-full ring-2 ring-white" />}
                        </button>
                    </div>
                </div>
            </header>

            {/* Progress Steps */}
            <div className="max-w-7xl mx-auto px-4 py-8">
                <div className="flex justify-between relative mb-12 max-w-3xl mx-auto">
                    {/* Connecting Line */}
                    <div className="absolute top-1/2 left-0 w-full h-0.5 bg-slate-200 -z-10 transform -translate-y-1/2 rounded-full overflow-hidden">
                        <div
                            className="h-full bg-gradient-to-r from-blue-600 to-purple-600 transition-all duration-500 ease-out"
                            style={{ width: `${((step - 1) / 3) * 100}%` }}
                        ></div>
                    </div>

                    {[
                        { id: 1, label: "Select", icon: FolderOpen },
                        { id: 2, label: "Analyze", icon: Sparkles },
                        { id: 3, label: "Review", icon: FileText },
                        { id: 4, label: "Upload", icon: UploadCloud },
                    ].map((s) => (
                        <div
                            key={s.id}
                            className={`flex flex-col items-center cursor-pointer group`}
                            onClick={() => step > s.id && setStep(s.id)}
                        >
                            <div
                                className={`w-10 h-10 rounded-full flex items-center justify-center border-2 transition-all duration-300 shadow-sm z-10
                  ${step === s.id
                                        ? 'bg-white border-purple-500 text-purple-600 scale-110 shadow-purple-200'
                                        : step > s.id
                                            ? 'bg-purple-50 border-purple-500 text-purple-600'
                                            : 'bg-white border-slate-300 text-slate-300'}
                `}
                            >
                                <s.icon className="w-4 h-4" />
                            </div>
                            <span className={`mt-2 text-xs font-bold uppercase tracking-wide transition-colors ${step === s.id ? 'text-purple-700' : 'text-slate-400'}`}>
                                {s.label}
                            </span>
                        </div>
                    ))}
                </div>

                {/* Main Content Area */}
                <div className="max-w-6xl mx-auto min-h-[600px]">
                    {step === 1 && renderStep1()}
                    {step === 2 && renderStep2()}
                    {step === 3 && renderStep3()}
                    {step === 4 && renderStep4()}
                </div>
            </div>
        </div>
    );
}
